title: "Welcome to Spress"
description: "A site created by Spress"
logo: "spresso-logo.png"

# Your site's domain. E.g: http://yoursite.com
url: ""

parsedown_actived: true

# Comments in posts
comments:
    enabled: false
    disqus_shortname: ""

# Information about author
author:
    name: "Your Name"

    # Social networks
    twitter: "spress_cms"
    github: "https://github.com/spress/Spress"
    bitbucket:
    facebook:
    linkedin:
    gplus:
    youtube:

# Collections
collections:
  posts:
    output: true

  projects:
    output: true

# RSS feed
feed:
    max_item: 10

# Facebook Open Graph
open_graph:
    locale: "en_US"

# Code highlight for <pre> and <code> tags
# Powered by http://highlightjs.org/
code_highlight: true

# Site validation
google_verify:
bing_verify:

# Page menus
top_menu:
    - { name: Home, url: "/" }
    - { name: Projects, url: "/projects" }

bottom_menu:
    - { name: "Go to the Spresso theme webpage", url: "https://github.com/yosymfony/Spress-theme-spresso" }
