title: "Welcome to Spress"
description: "A site creted by Spress"
logo: spresso-logo.png

# Your site's domain. E.g: http://yoursite.com
url: http://localhost:8080

# Information about author
author:
    name: Your Name
    
    # Social networks
    twitter: spress_cms
    github: https://github.com/yosymfony/Spress
    bitbucket:
    facebook:
    linkedin:
    gplus:
    youtube:
    
# Facebook Open Graph
open_graph:
    locale: en_US
    
# Code highlight for <pre> and <code> tags
# Powered by http://highlightjs.org/
code_highlight: true

# Site validation
google_verify:
bing_verify:

# Page menus
top_menu:
    - { name: Home, url: / }
    
bottom_menu:
    - { name: Go to Spresso theme web, url: https://github.com/yosymfony/Spress-theme-spresso }
    
paginate: 5

exclude: ['README.md', 'LICENSE','composer.json']